import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
YUKASSA_TOKEN = os.getenv("YUKASSA_TOKEN", "")

FREE_QUESTIONS_PER_DAY = 5
SUBSCRIPTION_PRICE_RUB = 199
SUBSCRIPTION_STARS = 100
SUBSCRIPTION_DAYS = 30